core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views
from .forms import LoginForm
from .views import userlogin, verify_otp

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    # path('login/', auth_views.LoginView.as_view(template_name = 'core/login.html', authentication_form = LoginForm), name = 'login'),
    path('login/', userlogin, name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify-otp/', verify_otp, name='verify-otp'),

]

dashboard/urls.py
from django.urls import path 

from . import views

app_name= 'dashboard'

urlpatterns = [
    path('', views.index , name='index'),
]

item/urls.py
from django.urls import path, include 
from .views import detail, new, delete, edit, items, add_to_cart, cart_items, delete_cart_item

app_name='item'

urlpatterns = [
    path('', items, name='items'),
    path('new/', new, name = 'new'),
    path('<int:pk>', detail, name='detail'),
    path('<int:pk>/delete/', delete, name='delete'),
    path('<int:pk>/edit/', edit, name='edit'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('cart_items/', cart_items, name='cart-items'),
    path('delete_cart_item/<str:itemid>/', delete_cart_item, name='delete-cart-item'),
]

# http://127.0.0.1:8000/items/add-to-cart/?item_id=16

payment/urls.py
from django.urls import path
from . import views

app_name='payment'

urlpatterns = [
    path('delivery_address/<str:subtotal>/<str:cartid>/', views.delivery_address, name='delivery-address'),
    path('place-order/', views.place_order, name='place_order'),
    path('order-confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('track-order/', views.track_order, name='track-order'),
]

tosar/urls.py
from django.urls import path 
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('', include('core.urls')),
    path('payment/', include('payment.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserOTP(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=55, blank=True, null=True)
    otp_code = models.CharField(max_length=6, null=True, blank=True)
    otp_created_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.user.username

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from core.models import UserOTP 

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget = forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full px-4 py-3 rounded-xl'
    }))

    password = forms.CharField(widget = forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'w-full px-4 py-3 rounded-xl'
    }))

class SignupForm (UserCreationForm):
    mobile = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Mobile Number',
        'class': 'w-full px-4 py-3 rounded-xl'
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget = forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full px-4 py-3 rounded-xl'
    }))

    email = forms.CharField(widget = forms.EmailInput(attrs={
        'placeholder': 'Your Email Address',
        'class': 'w-full px-4 py-3 rounded-xl'
    }))

    password1 = forms.CharField(widget = forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'value': '@Xuser123#',
        'class': 'w-full px-4 py-3 rounded-xl'
    }))

    password2 = forms.CharField(widget = forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'value': '@Xuser123#',
        'class': 'w-full px-4 py-3 rounded-xl'
    }))

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            # Save the mobile field in a separate model (e.g., UserOTP)
            UserOTP.objects.create(user=user, mobile=self.cleaned_data['mobile'])
        return user

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login
from core.models import UserOTP
from item.models import Category, Item
from .forms import SignupForm
import requests
import random
import uuid
from django.conf import settings
import re

def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()

    # return render(request, 'core/index.html', {
    #     'categories': categories,
    #     'items': items,
    # })
    return redirect('item:items')

def contact(request):
    return render(request, 'core/contact.html')

def verify_otp(request):
    if request.method == 'POST':
        userid = request.session.get('user_id')

        
        otp = request.POST.get('otp')

        if User.objects.filter(id=userid).exists():
            user = User.objects.get(id=userid)
            
            check = UserOTP.objects.filter(user=user, otp_code=otp).first()
             
            if check:
                login(request, user)
                return redirect('/')
            else:
                user_id = request.session.get('user_id')
                return render(request, 'core/otp.html', {"userid": user_id, 'error': 'Wrong OTP Code'})

        return redirect('core:login')

    elif not request.session.get('user_id'):
        return redirect('core:login')
    else:
        return render(request, 'core/otp.html')

def userlogin(request):
    if request.method == 'POST':
        
        phone = request.POST.get('phone')
        if not validate_bangladeshi_mobile_number(phone):
            return render(request, 'core/login.html', {"error": "Invalid Phone number"})
        
        phone = validate_bangladeshi_mobile_number(phone)

        if UserOTP.objects.filter(mobile=phone).exists():
            # random 6 digit otp code 
            otp_code = str(random.randint(100000, 999999))
            # Otp model
            otpModel = UserOTP.objects.get(mobile=phone)
            # Save randomly generated otp into otp model
            otpModel.otp_code = otp_code
            otpModel.save()
            # Send top to user phone number
            send_otp(otpModel)
            request.session['user_id'] = otpModel.user.id
            return redirect('core:verify-otp')
        else:
            return render(request, 'core/login.html', {"error": "User with this phone number does not exists!"})
    return render(request, 'core/login.html')

def signup(request):

    if request.method == 'POST':
        full_name = request.POST.get('fullname')
        mobile_number = request.POST.get('mobile')
        
        if not validate_bangladeshi_mobile_number(mobile_number):
            return render(request, 'core/signup.html', {"error": "Invalid mobile number!"})
        
        # Conver into valid mobile number if string exists it can detect it
        mobile_number = validate_bangladeshi_mobile_number(mobile_number)

        username = generate_unique_username()

        if mobile_number and full_name:
            if UserOTP.objects.filter(mobile=mobile_number).exists():
                return render(request, 'core/signup.html', {"error": "An account with this phone number already exists!"})
            else:
                new_user = User.objects.create_user(
                    username=username,
                    first_name=full_name,
                    password='@Xuser123$'
                )
                if new_user:
                    otp_code = str(random.randint(100000, 999999))
                    new_otp_model = UserOTP.objects.create(user=new_user, mobile=mobile_number, otp_code=otp_code)
                    send_otp(new_otp_model)
                    request.session['user_id'] = new_user.id
                    return redirect('core:verify-otp')
                else:
                    return render(request, 'core/signup.html', {"error": "New user creation failed! try again later."})
        else:
            return render(request, 'core/signup.html', {"error": "Full name and Mobile number is required!"})
     
    return render(request, 'core/signup.html')
 

def send_otp(userOtpModel):

    message = f"""
    Hi {userOtpModel.user.first_name},
    Your OTP code for Medicall+ is: {userOtpModel.otp_code}
    """
    url = "http://bulksmsbd.net/api/smsapi"
    params = {
        "api_key": settings.BULK_SMS_API_KEY,
        "type": "text",
        "number": userOtpModel.mobile,
        "senderid": settings.BULK_SMS_SENDER_ID,
        "message": message,
    }

    try:
        response = requests.get(url, params=params)
        # print("Bulk sms response", response)
        response.raise_for_status()  # Raise an error for bad HTTP status codes
        res = response.json()
        return res  # Parse and return the JSON response
    except requests.RequestException as e:
        return {"error": str(e)}
    

def generate_unique_username(base_name="user"):
    while True:
        unique_username = f"{base_name}_{uuid.uuid4().hex[:8]}"
        if not User.objects.filter(username=unique_username).exists():
            return unique_username
        
def validate_bangladeshi_mobile_number(number_str):
    pattern = r'^01[3-9]\d{8}$'
    if re.match(pattern, number_str):
        # Convert the valid string to an integer
        return int(number_str)
    else:
        # Return an error message if the number is invalid
        return False

core/templates/core/base.html
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" , content="width=device-width" , initial-scale="1.0">

    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <title>{% block title %} {% endblock %} | MediCall+ </title>
</head>

<body>
    <nav class="px-2 py-2 flex justify-between items-center border-b border-gray-200">
        <a href="/" , class="text-xl font-semibold text-teal-600">MediCall+</a>

        <div class="space-x-6">
            <div class="flex gap-3 justify-between items-center px-8"></div>
            <a href="{% url 'item:items' %}" , class="text-sm font-semibold hover:text-teal-400">Browse Medicine</a>

            {% if request.user.is_authenticated %}


            <a href="{% url 'item:cart-items' %}" , class="text-sm font-semibold hover:text-teal-400">
                Cart
                {% if cart_item_count > 0 %}
                <span
                    class="bg-red-600 text-white text-xs font-medium me-2 px-1.5 py-0.5 rounded-full dark:bg-red-600 dark:text-red-300">
                    {{cart_item_count}}
                </span>
                {% endif %}
            </a>
            <a href="{% url 'payment:track-order' %}" , class="text-sm text-green-600 font-semibold hover:text-teal-400">Track Orders</a>
            <!-- <a href="{% url 'dashboard:index' %}" , class="text-sm font-semibold hover:text-teal-400">Dashboard</a> -->
            <form method="post" class="inline" action="{% url 'core:logout' %}">
                {% csrf_token %}
                <button type="submit" class="text-sm text-red-600 font-semibold hover:text-red-800">Logout - ({{request.user.first_name}})</button>
            </form>


            {% else %}
            <a href="{% url 'core:signup' %}" , class="text-sm font-semibold hover:text-teal-400">Sign Up</a>
            <a href="{% url 'core:login' %}" , class="text-sm font-semibold hover:text-teal-400">Log in</a>
            {% endif %}

        </div>
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="px-6 py-3 flex justify-between">
        <div class="w-2/3 pr-10">

            <a href="/" , class="text-xl font-semibold text-teal-600">MediCall+</a>
            <p class="text-gray-400">Tosar Ahmed. <br> B.Sc in Software Engineering <br> at Daffodil International
                University.</p>
        </div>

        <div class=" ">
            <ul>
                <li><a href="#" , class="text-sm font-semibold hover:text-teal-400">About</a></li>
                <li><a href="{% url 'core:contact' %}" , class="text-sm font-semibold hover:text-teal-400">Contact</a>
                </li>
                <li><a href="#" , class="text-sm font-semibold hover:text-teal-400">Privacy Policy</a></li>
                <li><a href="#" , class="text-sm font-semibold hover:text-teal-400">Use of Terms</a></li>
            </ul>

        </div>

    </footer>
</body>

</html>

core/templates/core/card.html
<div class="h-screen w-full flex items-center justify-center  bg-gray-200 dark:bg-gray-800">
    <!-- product card -->
    <article class="max-w-sm w-full bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-700">
      <div>
        <img class="object-cover h-64 w-full" src="https://images.unsplash.com/photo-1542291026-7eec264c27ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0NzEyNjZ8MHwxfHNlYXJjaHw1fHxzbmVha2Vyc3xlbnwwfDB8fHwxNzEyMjIzNDAyfDA&ixlib=rb-4.0.3&q=80&w=1080" alt="Converse sneakers" />
      </div>
  
      <div class="flex flex-col gap-1 mt-4 px-4">
        <h2 class="text-lg font-semibold text-gray-800 dark:text-gray-50">Converse Sneakers</h2>
        <span class="font-normal text-gray-600 dark:text-gray-300">High Top (Lemon Yellow)</span>
        <span class="font-semibold text-gray-800 dark:text-gray-50">$60</span>
      </div>
  
      <div class="flex gap-4 mt-4 px-4">
        <span class="sr-only">Colors available</span>
  
        <button aria-label="Yellow" class="p-1 border border-gray-200 dark:border-gray-500 rounded-full cursor-pointer bg-yellow-500 dark:bg-yellow-400"></button>
  
        <button aria-label="Red" class="p-1 border border-gray-200 dark:border-gray-500 rounded-full cursor-pointer bg-red-500 dark:bg-red-400"></button>
  
        <button aria-label="Blue" class="p-1 border border-gray-200 dark:border-gray-500 rounded-full cursor-pointer bg-blue-500 dark:bg-blue-400"></button>
  
        <button aria-label="Black" class="p-1 border border-gray-200 dark:border-gray-500 rounded-full cursor-pointer bg-gray-800 dark:bg-gray-600"></button>
      </div>
  
      <div class="mt-4 p-4 border-t border-gray-200 dark:border-gray-500">
        <button class="w-full flex justify-between items-center font-bold cursor-pointer hover:underline text-gray-800 dark:text-gray-50">
          <span class="text-base">Add to Cart</span>
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
          </svg>
        </button>
      </div>
    </article>
  </div>

core/templates/core/contact.html
{% extends 'core/base.html' %}


{% block title %} Contact {% endblock %}
    
{% block content %}
    <h1>The contact Page</h1>
{% endblock%}

core/templates/core/index.html
{% extends 'core/base.html' %}


{% block title %} Welcome {% endblock %}
    
{% block content %}
<h2 class="mb-6 text-2xl text-center">Most popular Medicine</h2>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        
        <div class="grid grid-cols-5 gap-4">
            {% for item in items %}
            <div class="w-full flex items-center justify-center  bg-gray-200">
                <!-- product card -->
                <article class="max-w-sm w-full bg-gray-120 rounded-lg shadow-lg overflow-hidden ">
                  <div>
                    <img class="object-cover h-44 w-full" src="{{item.image.url}}" alt="Medicine" />
                  </div>
              
                  <div class="flex flex-col gap-1 mt-4 px-4">
                    <h2 class="text-sm font-semibold text-teal-800">{{item.name}}</h2>
                    <span class="font-semibold text-gray-800 ">TK {{item.price}}</span>
                  </div>
            
                  <div class="mt-4 p-4 border bg-teal-600 hover:bg-teal-500 border-teal-500">
                    <a href="{% url 'item:detail' item.id %}" class="w-full flex justify-between items-center font-bold cursor-pointer hover:underline text-gray-800 ">
                      <span class="text-base text-white rounded-full">Buy Now</span>
                      <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                      </svg>
                    </a>
                  </div>
                </article>
              </div>
            {% endfor %}
        </div>
            
    </div>>
{% endblock%}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title%} Login {% endblock %}

{% block content %}

<div class="w-1/3 my-6 mx-auto p-6 rounded-xl">
    <p class="text-xl font-semibold text-teal-600">MediCall+</p>
    <h1 class="mb-4 text-xl">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-2">
            <label class="inline-block mb-2">Phone Number</label><br>
            <input type="text" name="phone" placeholder="Your phone number" class="w-full px-4 py-3 rounded-xl">
        </div>

        
        <button class="px-3 py-1 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Log in</button>

    </form>
</div>

{% endblock %}

core/templates/core/otp.html
{% extends 'core/base.html' %}

{% block title%} Login {% endblock %}

{% block content %}

<div class="w-1/3 my-6 mx-auto p-6 rounded-xl">
    <p class="text-xl font-semibold text-teal-600">MediCall+</p>
    <h1 class="mb-4 text-xl">Verify OTP</h1>

    <form method="POST" action="{% url 'core:verify-otp' %}">
        {% csrf_token %}
        {% if error %}
            <p class="text-red-600 font-semibold py-3">{{error}}</p>
        {% endif %}
        <div class="mb-2">
            <label class="inline-block mb-2">OTP Code</label><br>
            <input type="text" name="otp" placeholder="Your otp code" class="w-full px-4 py-3 rounded-xl">
        </div>

        
        <button type="submit" class="px-3 py-1 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Verify</button>

    </form>
</div>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title%}Sign Up{% endblock %}

{% block content %}

<div class="w-1/3 my-2 mx-auto p-2 rounded-xl">
    <h1 class="mb-2 text-3xl">Sign Up</h1>

    <form method="POST" action="{% url 'core:signup' %}">
        {% csrf_token %}
        {% if error %}
            <p class="text-red-600 font-semibold py-3">{{error}}</p>
        {% endif %}
        <div class="mb-2">
            <label class="inline-block mb-2">Full Name</label><br>
            <input type="text" placeholder="Your Full Name" name="fullname" class='w-full px-4 py-3 rounded-xl'>
        </div>

        <div class="mb-2">
            <label class="inline-block mb-2">Mobile</label><br>
            <input type="text" placeholder="Your Mobile Number" name="mobile" class='w-full px-4 py-3 rounded-xl'>
        </div>

        
        <div class="flex justify-between items-center">
            <button class="px-3 py-2 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Register New Account</button>

            <a href="{% url 'core:login' %}", class=" hover:text-teal-400">Already have an account</a>

        </div>
    </form>
</div>

{% endblock %}