core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views
from .forms import LoginForm
from .views import userlogin, verify_otp

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    # path('login/', auth_views.LoginView.as_view(template_name = 'core/login.html', authentication_form = LoginForm), name = 'login'),
    path('login/', userlogin, name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify-otp/', verify_otp, name='verify-otp'),

]

item/urls.py
from django.urls import path, include 
from .views import detail, new, delete, edit, items, add_to_cart, cart_items, delete_cart_item

app_name='item'

urlpatterns = [
    path('', items, name='items'),
    path('new/', new, name = 'new'),
    path('<int:pk>', detail, name='detail'),
    path('<int:pk>/delete/', delete, name='delete'),
    path('<int:pk>/edit/', edit, name='edit'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('cart_items/', cart_items, name='cart-items'),
    path('delete_cart_item/<str:itemid>/', delete_cart_item, name='delete-cart-item'),
]

# http://127.0.0.1:8000/items/add-to-cart/?item_id=16

payment/urls.py
from django.urls import path
from . import views

app_name='payment'

urlpatterns = [
    path('delivery_address/<str:subtotal>/<str:cartid>/', views.delivery_address, name='delivery-address'),
    path('place-order/', views.place_order, name='place_order'),
    path('order-confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('track-order/', views.track_order, name='track-order'),
]

tosar/urls.py
from django.urls import path 
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('', include('core.urls')),
    path('payment/', include('payment.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)
    order = models.IntegerField(default=1)

    class Meta:
        ordering = ('name',)
        verbose_name_plural= 'Categories'

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    mg = models.TextField(max_length=50, blank=True, null=True, verbose_name="Unit")
    group = models.TextField(max_length=255, blank=True, null=True)
    company = models.TextField(max_length=255, blank=True, null=True)
    short_description = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    
    price = models.FloatField()
    image = models. ImageField(upload_to = 'items images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
   
    def __str__(self):
        return str(self.user.id)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cart_items")
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id) + " - " + str(self.cart.user.username) + " - " +  str(self.item.name)

item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q 
from django.shortcuts import render, get_object_or_404, redirect 
from .models import Category
from .models import Item, Cart, CartItem
from django.http import JsonResponse
from .forms import NewItemForm, EditItemForm
from django.shortcuts import get_object_or_404, redirect
from django.core.serializers import serialize

def safe_parse_int(value, base=10):
    try:
        return int(value, base)
    except ValueError:
        return None

def items(request):
    query = request.GET.get('query', '')
    search_category = request.GET.get('category', '')
    categories = Category.objects.all().order_by('order')
    items = Item.objects.filter(is_sold=False)
 
    current_category = ""
    if search_category:
        current_category = Category.objects.get(id=search_category).name
    if search_category:
        items = items.filter(category_id=search_category)
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'search_category': safe_parse_int(search_category),
        'current_category': current_category,
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)

    return render(request, 'item/detail.html', {
        'item': item,
    })

def add_to_cart(request):
    item_id = request.GET.get('item_id')
    quantity = int(request.GET.get('quantity', 1))  # Default to 1 if quantity is not provided

    if not item_id:
        return JsonResponse({'error': 'Item ID is required'}, status=400)

    # Retrieve the item object
    item = get_object_or_404(Item, id=item_id)

    # Simulate a user cart; in a real scenario, this could be linked to the logged-in user
    cart, created = Cart.objects.get_or_create(user=request.user)

    # Check if the item is already in the cart
    cart_item, created = CartItem.objects.get_or_create(cart=cart, item=item)

    if not created:
        # If the item is already in the cart, update the quantity
        cart_item.quantity += quantity
        cart_item.save()
        return JsonResponse({'message': f'Updated quantity for {item.name} to {cart_item.quantity}'}, status=200)
    else:
        # If the item is not in the cart, set the initial quantity
        cart_item.quantity = quantity
        cart_item.save()
        return JsonResponse({'message': f'Added {item.name} to cart with quantity {quantity}'}, status=200)

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect ('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New item',
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect ('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })

@login_required
def delete(request, pk):
    item.delete()

    return redirect('dashboard:index')


@login_required
def delete_cart_item(request, itemid):

    
    # cart = Cart.objects.get(user=request.user)
    
    cart_item = CartItem.objects.get(id=itemid)
    # Delete the CartItem
    cart_item.delete()

    # print(cart_item)
    return redirect('item:cart-items')
    # else:
    #     return redirect('/')


@login_required
def cart_items(request):
    
    cart = Cart.objects.get(user=request.user)
    cart_items = CartItem.objects.filter(cart=cart)
    cart_total = sum(cart_item.item.price * cart_item.quantity for cart_item in cart.cart_items.all())

    for cart in cart_items:
        cart.total_price = cart.item.price * cart.quantity

    return render(request, 'item/cart_items.html', {'cart_items': cart_items, 'cart_total': cart_total, 'cart_id': cart.id})

item/templates/item/cart_items.html
{% extends 'core/base.html' %}

{% block title %}{{item.name}} {% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-8">Your Cart</h1>

    {% if cart_items %}
        <div class="grid grid-cols-4">
            <div class="bg-white shadow-md rounded-lg overflow-hidden col-span-3">
                <table class="w-full">
                    <thead>
                        <tr class="bg-gray-100">
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Product</th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Quantity</th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Price</th>
                            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200">
                        {% for cart in cart_items %}
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="flex items-center">
                                        {% if cart.item.image %}
                                            <img class="h-16 w-16 rounded-full mr-3" src="{{ cart.item.image.url }}" alt="{{ item.name }}">
                                        {% endif %}
                                        <div class="text-sm font-medium text-gray-900">
                                            <p class="text-lg">{{ cart.item.name }}</p>
                                            <span class="text-sm text-gray-500">{{ cart.item.category.name }} |  {{ cart.item.mg }} | {{ cart.item.company }}</span>
                                        </div>
                                    </div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-900">{{ cart.quantity }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-900">Per Unit <span class="font-bold">{{ cart.item.price|floatformat:2 }}</span> TK</div>
                                </td>
                                
                                
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <form method="post" action="{% url 'item:delete-cart-item' itemid=cart.id %}" class="flex items-center">
                                        {% csrf_token %}
                                         
                                        <button type="submit" class="ml-2 px-3 py-1 bg-red-500 text-white rounded-md hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50">
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    
            <div class="mt-8 bg-white shadow-md rounded-lg p-6">
                <p class="font-bold text-xl mb-1">Products</p>
                {% for cart in cart_items %}
                    <span class="text-gray-600 font-semibold py-2">{{cart.item.category.name}} - {{cart.item.price}} x {{cart.quantity}} = {{cart.total_price}} </span><br>
                {% endfor %}
                <div class="flex justify-between items-center mt-4">
                    
                    <span class="text-lg font-semibold">Total:</span>
                    <span class="text-2xl font-bold">{{ cart_total|floatformat:2 }} TK</span>
                </div>
                <div class="mt-6">
                    <a href="{% url 'payment:delivery-address' subtotal=cart_total cartid=cart_id %}" class="w-full bg-teal-500 text-white py-2 px-4 rounded-md hover:bg-teal-600 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-opacity-50 inline-block text-center">
                        Proceed to Checkout
                    </a>
                </div>
            </div>
        </div>
    {% else %}
        <div class="bg-white shadow-md rounded-lg p-6 text-center">
            <p class="text-xl">Your cart is empty.</p>
            <a href="" class="mt-4 inline-block bg-teal-500 text-white py-2 px-4 rounded-md hover:bg-teal-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50">
                Continue Shopping
            </a>
        </div>
    {% endif %}
</div>
{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{item.name}} {% endblock %}

{% block content %}
<!-- <div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{item.image.url}}" class="rounded-xl">
    </div>
</div> -->
<div class="container mx-auto px-4 py-8">
    <div class="flex flex-col md:flex-row gap-8 mb-12">
        <!-- Left side - Medicine Image -->
        <div class="md:w-1/2">
            <div class="bg-white p-4 rounded-lg shadow-md">
                <img src="{{item.image.url}}" alt="Medicine Name" class="w-full h-auto rounded-lg shadow-lg">
            </div>
        </div>

        <!-- Right side - Basic Info, Price, and Add to Cart -->
        <div class="md:w-1/2">
            <h1 class="text-2xl font-bold mb-4">{{item.name}}</h1>
            <!-- <div class="flex items-center mb-4">
                <div class="flex">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-yellow-400 fill-current" viewBox="0 0 20 20">
                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-yellow-400 fill-current" viewBox="0 0 20 20">
                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-yellow-400 fill-current" viewBox="0 0 20 20">
                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-yellow-400 fill-current" viewBox="0 0 20 20">
                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-yellow-400 fill-current" viewBox="0 0 20 20">
                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                </div>
                <span class="ml-2 text-gray-600">(128 reviews)</span>
            </div> -->
            <p class="text-base font-semibold mb-4 italic">{{item.short_description}}</p>
            <div class="mb-6">
                <h2 class="text-base font-semibold mb-2">Key Information:</h2>
                <ul class="list-disc list-inside text-gray-700">
                    <li>Unit/Dose: {{item.mg}}</li>
                    <li>Group: {{item.group}}</li>
                    <li>Company: {{item.company}}</li>
                </ul>
            </div>
            <div class="flex items-center justify-between mb-6">
                <span class="text-3xl font-bold text-primary"> {{item.price}} TK</span>
                <div class="flex items-center justify-between gap-6">
                    <div class="">
                        <div class="flex items-center border border-gray-300 rounded-md">
                            <button id="decrease"
                                class="px-4 py-2 bg-gray-100 text-gray-600 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500 rounded-l-md">
                                -
                            </button>
                            <input type="number" id="quantity" value="1" min="1" max="100"
                                class="w-16 px-2 py-2 text-center border-x border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500">
                            <button id="increase"
                                class="px-4 py-2 bg-gray-100 text-gray-600 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500 rounded-r-md">
                                +
                            </button>
                        </div>
                    </div>
                    {% if user.is_authenticated %}
                    <button onclick="addToCart({{item.id}})"
                        class="bg-teal-600 hover:bg-teal-500 text-white font-bold py-2 px-4 rounded flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                        </svg>
                        Add to Cart
                    </button>
                    {% else %}
                    <a href="{% url 'core:login' %}"
                        class="bg-teal-600 hover:bg-teal-500 text-white font-bold py-2 px-4 rounded flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                        </svg>
                        Add to Cart
                    </a>
                    {% endif %}
                </div>
            </div>

            <div class="bg-blue-100 text-blue-800 p-4 rounded-lg">
                <h3 class="font-semibold mb-2">Important Information:</h3>
                <p>Please consult with a healthcare professional before use. Keep out of reach of children.</p>
            </div>
        </div>
    </div>

    <!-- Bottom - Detailed Description -->
    <div class="bg-white rounded-lg shadow-md mt-8 p-6">
        <h2 class="text-2xl font-bold mb-4">Detailed Description</h2>
        {{item.description}}
    </div>

    <script>
        // Item quantity
        const decreaseBtn = document.getElementById('decrease');
        const increaseBtn = document.getElementById('increase');
        const quantityInput = document.getElementById('quantity');

        decreaseBtn.addEventListener('click', () => {
            if (quantityInput.value > 1) {
                quantityInput.value = parseInt(quantityInput.value) - 1;
            }
        });

        increaseBtn.addEventListener('click', () => {
            if (quantityInput.value < 100) {
                quantityInput.value = parseInt(quantityInput.value) + 1;
            }
        });

        quantityInput.addEventListener('change', () => {
            let value = parseInt(quantityInput.value);
            if (isNaN(value) || value < 1) {
                quantityInput.value = 1;
            } else if (value > 100) {
                quantityInput.value = 100;
            }
        });
        // Add to cart
        async function addToCart(itemId) {
            quantity = quantityInput.value
            console.log(itemId)
            console.log(quantity)
            console.log('Quanitty', quantity)
            const url = `/items/add-to-cart/?item_id=${itemId}&quantity=${quantity}`;
            console.log('Generated URL: ', url)
            try {
                const response = await fetch(url, {
                    method: 'GET', // Use 'POST' if your backend expects it
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': getCookie('csrftoken') // Ensure CSRF token is included for authenticated requests
                    }
                });

                if (response.ok) {
                    const data = await response.json();
                    // alert(data.message); // Display success message
                    location.reload();
                } else {
                    const errorData = await response.json();
                    alert(`Error: ${errorData.error || 'Failed to add item to cart'}`);
                }
            } catch (error) {
                console.error('Error:', error);
                alert('An unexpected error occurred. Please try again.');
            }
        }

        // Helper function to get CSRF token from cookies
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Check if this cookie string begins with the name we want
                    if (cookie.startsWith(name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        
    </script>
</div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %} {{title }} {% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{title}}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
    {% endif %}
        <button class="mt-6 px-6 py-3 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>

{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}

    <div class="pb-6 grid grid-cols-5 gap-4">
        
        <div class="col-span-1  bg-gray-100 py-3 px-2 rounded-md">
            <form method="get", action="{% url 'item:items' %}">
                <div class="flex justify-between items-center gap-2">
                    <input name="query" class="w-full px-1 py-1 border rounded-xl" type="text" value="{{ guery }}" placeholder="Find your items ....">
                    <button class="py-1 px-1 text-sm bg-teal-500 text-white rounded-xl">Search</button>
                </div>
            </form>

            <hr class="my-6">
            <p class="font-semibold">Categories</p>

            <ul>
           
                {% for category in categories %}

                    <!-- <li class="px-2 py-2 rounded-xl bg-teal-400 my-2 {% if search_category == category.id %} bg-blue-600 {% endif %}"> -->
                    <li class="{% if category.id == search_category %}
                                px-2 py-2 rounded-xl bg-teal-400 my-2 text-white font-semibold
                              {% else %}
                                px-2 py-2 rounded-xl my-2
                              {% endif %}">    
                      <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name}} </a>
                    </li>

                {% endfor %}

            </ul>
            <hr class="my-6">
            <p class="font-semibold">Clear Filter</p>

            <ul>
                <li>
                    <a href="/items/" class="mt-1 px-2 bg-teal-500 rounded-xl inline-block text-lg font-sm text-white hover:bg-yellow-800">Clear</a></li>
            </ul>

        </div>

        <div class="col-span-4">
            {% if current_category %}
            <div class="py-3">
              <a href="/"><span class="bg-gray-400 text-white rounded px-2 text-center pb-1 hover:bg-gray-500">Home ></span></a>
              <span class="bg-gray-400 text-white rounded px-2 text-center pb-1">{{current_category}}</span>
            </div>
            {% endif %}
            <div class="grid grid-cols-4 gap-4  ">
                {% for item in items %}
                <div class="w-full flex items-center justify-center  bg-gray-200">
                    <!-- product card -->
                    <article class="max-w-sm w-full bg-gray-120 rounded-lg shadow-lg overflow-hidden ">
                      <div>
                        <img class="object-cover h-44 w-full" src="{{item.image.url}}" alt="Medicine" />
                      </div>
                  
                      <div class="flex flex-col gap-1 mt-4 px-4">
                        <h2 class="text-lg font-bold text-teal-800">{{item.name}}</h2>
                        <span class="font-bold text-gray-800 ">TK {{item.price}}</span>
                      </div>
                
                      <div class="mt-4 p-4 border bg-teal-600 hover:bg-teal-500 dark:border-teal-500">
                        <a href="{% url 'item:detail' item.id %}" class="w-full flex justify-between items-center font-bold cursor-pointer hover:underline text-gray-800 ">
                          <span class="text-base text-white rounded-full">Buy Now</span>
                          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                          </svg>
                        </a>
                      </div>
                    </article>
                  </div>
                {% endfor %}
            </div>
        </div>

    </div>

{% endblock %}